/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ArchivRouteImport } from './routes/archiv'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KlipyRouteImport } from './routes/klipy'
import { Route as AuthenticatedModeraceRouteImport } from './routes/_authenticated/moderace'
import { Route as AuthenticatedPrilozitRouteImport } from './routes/_authenticated/prilozit'
import { Route as AuthenticatedSpravaRoliRouteImport } from './routes/_authenticated/sprava-roli'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivRoute = ArchivRouteImport.update({
  id: '/archiv',
  path: '/archiv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KlipyRoute = KlipyRouteImport.update({
  id: '/klipy',
  path: '/klipy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModeraceRoute = AuthenticatedModeraceRouteImport.update({
  id: '/moderace',
  path: '/moderace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrilozitRoute = AuthenticatedPrilozitRouteImport.update({
  id: '/prilozit',
  path: '/prilozit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpravaRoliRoute = AuthenticatedSpravaRoliRouteImport.update({
  id: '/sprava-roli',
  path: '/sprava-roli',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archiv': typeof ArchivRoute
  '/auth': typeof AuthRoute
  '/klipy': typeof KlipyRoute
  '/moderace': typeof AuthenticatedModeraceRoute
  '/prilozit': typeof AuthenticatedPrilozitRoute
  '/sprava-roli': typeof AuthenticatedSpravaRoliRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archiv': typeof ArchivRoute
  '/auth': typeof AuthRoute
  '/klipy': typeof KlipyRoute
  '/moderace': typeof AuthenticatedModeraceRoute
  '/prilozit': typeof AuthenticatedPrilozitRoute
  '/sprava-roli': typeof AuthenticatedSpravaRoliRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/archiv': typeof ArchivRoute
  '/auth': typeof AuthRoute
  '/klipy': typeof KlipyRoute
  '/_authenticated/moderace': typeof AuthenticatedModeraceRoute
  '/_authenticated/prilozit': typeof AuthenticatedPrilozitRoute
  '/_authenticated/sprava-roli': typeof AuthenticatedSpravaRoliRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archiv'
    | '/auth'
    | '/klipy'
    | '/moderace'
    | '/prilozit'
    | '/sprava-roli'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archiv'
    | '/auth'
    | '/klipy'
    | '/moderace'
    | '/prilozit'
    | '/sprava-roli'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/archiv'
    | '/auth'
    | '/klipy'
    | '/_authenticated/moderace'
    | '/_authenticated/prilozit'
    | '/_authenticated/sprava-roli'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArchivRoute: typeof ArchivRoute
  AuthRoute: typeof AuthRoute
  KlipyRoute: typeof KlipyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv': {
      id: '/archiv'
      path: '/archiv'
      fullPath: '/archiv'
      preLoaderRoute: typeof ArchivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klipy': {
      id: '/klipy'
      path: '/klipy'
      fullPath: '/klipy'
      preLoaderRoute: typeof KlipyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moderace': {
      id: '/_authenticated/moderace'
      path: '/moderace'
      fullPath: '/moderace'
      preLoaderRoute: typeof AuthenticatedModeraceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prilozit': {
      id: '/_authenticated/prilozit'
      path: '/prilozit'
      fullPath: '/prilozit'
      preLoaderRoute: typeof AuthenticatedPrilozitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprava-roli': {
      id: '/_authenticated/sprava-roli'
      path: '/sprava-roli'
      fullPath: '/sprava-roli'
      preLoaderRoute: typeof AuthenticatedSpravaRoliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedModeraceRoute: typeof AuthenticatedModeraceRoute
  AuthenticatedPrilozitRoute: typeof AuthenticatedPrilozitRoute
  AuthenticatedSpravaRoliRoute: typeof AuthenticatedSpravaRoliRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedModeraceRoute: AuthenticatedModeraceRoute,
  AuthenticatedPrilozitRoute: AuthenticatedPrilozitRoute,
  AuthenticatedSpravaRoliRoute: AuthenticatedSpravaRoliRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArchivRoute: ArchivRoute,
  AuthRoute: AuthRoute,
  KlipyRoute: KlipyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
